#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - echo ${dockerhub_token} | docker login -u ${dockerhub_username} --password-stdin
  - docker pull ${docker_image}:${image_tag}
  - docker run -d -p 80:80 --name assetrix-app ${docker_image}:${image_tag}
